### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ZeroEkkusu** [onbjerg/foundry-book#87]
Which one?

**Comment by ZeroEkkusu** [comment]
Which license is the repo licensed under?

**Comment by onbjerg** [comment]
Apache/MIT dual license is super common in the Rust ecosystem - AFAIK it gives end-users the option to choose. Personally, I hate licensing talks since I don't really speak legalese, so I just opt for the same licenses most of the time. Some rationale can be found here: https://github.com/sfackler/rust-postgres-macros/issues/19 and here: https://github.com/dtolnay/rust-faq#why-a-dual-mitasl2-license

**Comment by ZeroEkkusu** [comment]
Thanks! I always want to learn more about legal stuff.
